apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pythonapi
  namespace: w255
spec:
  selector:
    matchLabels:
      app: pythonapi
  replicas: 3
  template:
    metadata:
      labels:
        app: pythonapi
    spec:
      initContainers:
        - name: init-redis-up
          image: busybox
          command: ["sh", "-c", "until nslookup redis-service.w255.svc.cluster.local; do echo 'waiting for redis'; sleep 5; done"]
        - name: init-redis-ready
          image: busybox
          command: ["sh", "-c", "until nslookup redis-service.w255.svc.cluster.local; do echo 'waiting for redis'; sleep 5; done"]
      containers:
      - name: lab4
        image: lab4_deployed:1.0
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 60
