apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: w255
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        command: ["redis-server"] #made this change
        ports:
          - containerPort: 6379
