apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: w255
spec:
  type: LoadBalancer
  selector:
    app: pythonapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
