---
apiVersion: v1
kind: Service
metadata:
  name: project
  labels:
    app: project
spec:
  type: ClusterIP #ClusterIP
  #change to LoadBalancer when testing locally
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: project
